### ISSUE TITLE
scope does not work? 

### ISSUE THREAD

**Issue by BenK3nobi** [sergey-inform/SIS3316#5]
Hello everybody, 

I found this repository while I was trying to readout the SIS during an upcoming beamtime. 
Everything works good so far. Thanks a lot for sharing your code on github. 

For the debugging of the system I planned to use the scope that was implemented. 
When I started it I got the following output: 

Traceback (most recent call last):
  File "scope.py", line 472, in OnInit
    self.frame = MainFrame(None, -1)
  File "scope.py", line 378, in __init__
    self.create_main_panel()
  File "scope.py", line 400, in create_main_panel
    self.waveform = WaveformPanel(self.panel)
  File "scope.py", line 198, in __init__
    csizer.Add(self.baseline, 0, flag=wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_RIGHT)
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at /tmp/pip-build-OfWMAN/wxpython/ext/wxWidgets/src/common/sizer.cpp(2098) in DoInsert(): Horizontal alignment flags are ignored in horizontal sizers
OnInit returned false, exiting...

I am a little clueless, any ideas how to fix that? 

Cheers

**Comment by dougUCN** [comment]
Seems to be mostly a wxPython related bug, that I don't know how to fix since I can't replicate this issue on my machine

If you are looking for a quick signal readout from the sis3316 to test things, I'd recommend just using `tools/conf.py` to load in a config file, do a readout using `tools/readout.py`, and then to parse + plot the data file. 

I have attached a parsing sample script (github only allows me to upload text, obviously delete the '.txt' part)

[quickParse.py.txt](https://github.com/sergey-inform/SIS3316/files/5398093/quickParse.py.txt)

Please note that the sample `config.in` file currently tells the sis3316 to not log the raw signal. To enable, set the `raw_window` field under "groups" to the value `gate_window` is set at. (Warning, this will make your output files fairly large, I'd recommend enabling accumulator gate logging during an actual beam run instead of trying to save complete signals)

Also, if you are looking to have a GUI to run the sis3316 and to live plot the ADC spectrum or something of the sort, I have a GUI that I can send you (using PyQt5 and pyqtgraph). Maybe that will run on your machine better, please send me an email if you are interested in that. Everyone's GUI needs are different, though, maybe you'll just want to code your own (now that sis3316 interfacing is taken care of nicely with this code repository)

**Comment by BenK3nobi** [comment]
Okay, thanks a lot. I try my best to solve the issue. 
You should also have an email by now :)

**Comment by BenK3nobi** [comment]
So I am going to close this issue.
The beam time I had was successful, unfortunately I did not get the python version running in time. 
Control and readout are now working for the next beam time during summer, so this is all fine.
